---
title: "Practicum Predictive"
author: "Team"
date: "3/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(tidyverse)
library(lubridate)
library(ggthemes)
library(data.table)
library(scales)
```

```{r new, cache=T}
newwo = read_csv("workorder_clean.csv", guess_max = 1500000)
```

### Data Manipulations

```{r date}
requested = newwo %>% 
  mutate(yearrequested = year(daterequested),
         monthrequested = month(daterequested),
         dayrequested = day(daterequested)) %>%
  filter(yearrequested < 2020, yearrequested > 2000) %>%
  mutate(ymrequested = make_date(yearrequested, monthrequested),
         ymdrequested = make_date(yearrequested, monthrequested, dayrequested)) %>%
  mutate(yearcompleted = year(actualcompletiondate),
         monthcompleted = month(actualcompletiondate),
         daycompleted = day(actualcompletiondate)) %>%
  filter(yearcompleted < 2020, yearcompleted > 2000) %>%
  mutate(ymcompleted = make_date(yearcompleted, monthcompleted),
         ymdcompleted = make_date(yearcompleted, monthcompleted, daycompleted))

```

```{r priorityts}
priority = requested %>% select(craftdescription, craftgroup, daterequested, datecreated, actualcompletiondate, laststatuschange, currentstatus, prioritydescription, ispreventmaint, ymrequested, ymcompleted) %>%
  filter(currentstatus %in% c("Completed", "Closed")) %>%
  filter(prioritydescription != "OTHER") %>%
  filter(!is.na(daterequested), !is.na(datecreated), !is.na(laststatuschange)) %>%
  mutate(createffi = abs(as.numeric(round((datecreated - daterequested)/3600), digits = 2)),
         totaleffi = abs(as.numeric(round((actualcompletiondate - daterequested)/3600), digits = 2)))

priority
```

### Cost Analysis

1. Subsets

```{r cost}
zerocost = newwo %>% filter(actualcosts == 0, 
                            currentstatus == "Completed") %>% 
  select(craftgroup, prioritydescription) %>%
  group_by(craftgroup) %>%
  summarize(n = n())

costdata = requested %>% filter(currentstatus %in% c("Completed", "Closed"),
                                !is.na(daterequested), 
                                !is.na(datecreated), 
                                !is.na(laststatuschange)) %>%
  filter(prioritydescription != "OTHER") %>%
  select(actualcosts, craftgroup, daterequested, actualcompletiondate, prioritydescription, ymrequested, ymcompleted) %>% 
  mutate(totaleffi = abs(as.numeric(round((actualcompletiondate - daterequested)/3600), digits = 2)))

zerocost = costdata %>% filter(actualcosts == 0)
nonzerocost = costdata %>% filter(actualcosts != 0)
normalcost = costdata %>% filter(actualcosts < 3500, actualcosts > 0)
mediumcost = costdata %>% filter(actualcosts >= 3500, actualcosts <= 10000)
highcost = costdata %>% filter(actualcosts > 10000)
```

2. Regression

```{r costreg}
regall = lm(actualcosts ~ craftgroup + totaleffi + prioritydescription, data = costdata)
summary(regall)

regnonzero = lm(actualcosts ~ craftgroup + totaleffi + prioritydescription, data = nonzerocost)
summary(regnonzero)

regnormal = lm(actualcosts ~ craftgroup + totaleffi + prioritydescription, data = normalcost)
summary(regnormal)

regmedium = lm(actualcosts ~ craftgroup + totaleffi + prioritydescription, data = mediumcost)
summary(regmedium)

reghigh = lm(actualcosts ~ craftgroup + totaleffi + prioritydescription, data = highcost)
summary(reghigh)
```

3. Time Series 


3.1. Time series by requested date to predict number of orders requested

```{r wocount}
wocount = nonzerocost  %>% group_by(ymrequested) %>% summarize(wocount = n())
```

```{r wocountts}
wocountts = ts(wocount$wocount, start = c(2001,1), end = c(2019,8), frequency = 12)
plot(wocountts)
```

```{r wocountts_testMSE_alldata}
train.periods <- 150
test.periods <- 67
cycle <- 12

wocountts.training <- ts(wocount$wocount[1:train.periods], start = c(2001,1), end = c(2019,8), frequency = 12)

wocountts.training.SESmodel <- HoltWinters(wocountts.training, beta=FALSE, gamma=FALSE)
wocountts.training.DESmodel <- HoltWinters(wocountts.training, gamma=FALSE)
wocountts.training.HWmodel <- HoltWinters(wocountts.training)

wocountts.SESmodel <- HoltWinters(wocountts,
                          alpha=wocountts.training.SESmodel$alpha, 
                          beta=FALSE, 
                          gamma=FALSE)
wocountts.DESmodel <- HoltWinters(wocountts, 
                          alpha=wocountts.training.DESmodel$alpha, 
                          beta=wocountts.training.DESmodel$beta, 
                          gamma=FALSE)
wocountts.HWmodel <- HoltWinters(wocountts, 
                         alpha=wocountts.training.HWmodel$alpha, 
                         beta=wocountts.training.HWmodel$beta, 
                         gamma=wocountts.training.HWmodel$gamma)

data.start <- train.periods + 1
data.end <- train.periods + test.periods

fit.start <- train.periods 
fit.end <- train.periods + test.periods - 1

SES.MSE <- sum((wocountts.SESmodel$fitted[fit.start:fit.end] - wocountts[data.start:data.end])^2)/(test.periods)

fit.start <- train.periods - 1 
fit.end <- train.periods + test.periods - 2

DES.MSE <- sum((wocountts.DESmodel$fitted[fit.start:fit.end] - wocountts[data.start:data.end])^2)/(test.periods)

fit.start <- train.periods - cycle + 1 
fit.end <- train.periods + test.periods - cycle

HW.MSE <- sum((wocountts.HWmodel$fitted[fit.start:fit.end] - wocountts[fit.start:fit.end])^2)/(test.periods)

cat(paste("SES MSE =", SES.MSE, "\nDES MSE =", DES.MSE, "\nHW MSE =", HW.MSE))
```

```{r wocountts_predict}
plot(wocountts.HWmodel)
wocount_2020_HW = forecast(wocountts.HWmodel, 15)
plot(wocount_2020_HW, main = "Holtwinters Forecast for 2019-2020")
```



3.2. Time Series by requested date to predict total costs

```{r setupts}
costts = nonzerocost %>% select(actualcosts, ymrequested)
normalcostts = normalcost %>% select(actualcosts, ymrequested)
mediumcostts = mediumcost %>% select(actualcosts, ymrequested)
highcostts = highcost %>% select(actualcosts, ymrequested)
```

```{r costts}
totalts = ts(costts$actualcosts, start = 2001, end = 2019, frequency = 12)
```

### Priority Time Series



### Efficiency Time Series

1. Request-Created Efficiency

2. Request-Completed Efficiency
